name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'hotfix/*'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code_formatting_job:
    name: Code Formatting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Debug ktlint
        run: ./gradlew --no-daemon ktlintCheck --continue

      - name: Upload ktlint Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ktlint-report
          path: '**/build/reports/ktlint'
          retention-days: 1

  lint_job:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Debug Lint
        run: ./gradlew --no-daemon lintDebug

      - name: Upload Lint Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: '**/build/reports/lint-results-*'
          retention-days: 1

  assemble_job:
    needs: [ code_formatting_job, lint_job ]
    name: Assemble
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Assemble Debug
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: catalog/build/outputs/apk/debug/**.apk
          retention-days: 7
