name: Dokka GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GRADLE_ARGS: >-
        --no-daemon
        --max-workers 2
        -Pkotlin.incremental=false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Dokka
        run: ./gradlew $GRADLE_ARGS dokkaHtmlMultiModule

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/dokka/htmlMultiModule
